language: perl
perl:
  - "5.30"
services:
  - mysql
  - postgresql
addons:
  apt:
    packages:
      - libdb-dev
before_script:
  - cpanm Test::Pod DB_File # optional dependencies
  - psql -c 'create database test;' -U postgres
